name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install Just
        run: sudo apt-get update && sudo apt-get install -y just
        shell: bash

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: just test-coverage
        shell: bash
